### ISSUE TITLE
Can't Install the theme

### ISSUE THREAD

**Issue by ComicBit** [hotdoy/grav-theme-hotdoy#12]
Trying to install the theme and I always have this Error (Code: 200) "Transferred a partial file transfer closed with outstanding read data remaining". I even tried to download the package from Grav website and push it manually from Direct Install, still. It doesn't work in any case. I wanted to contact you somehow but looks like it's totally impossible to get in contact with you.

**Comment by vincentrouleau** [comment]
Well it looks like you found a way. :)
Did you try to install the theme or the skeleton?
Can you give me any information on your setup?

**Comment by vincentrouleau** [comment]
200 is usually a success. Seems weird enough.

**Comment by hotdoy** [comment]
It's been. While since I've installed my own theme. I'll try it out sometimes today.

**Comment by vincentrouleau** [comment]
I was able to install the theme successfully in local. 
Downloaded the Grav Admin package from getgrav.org
Then downloaded the Hotdoy theme from the admin panel.

**Comment by vincentrouleau** [comment]
CHANGELOG date format has been fixed and the demo content folder has been removed from the latest releases. (v1.5.7 and up).

**Comment by vincentrouleau** [comment]
@ComicBit any feedback is appreciated. Else I'll just close the issue and consider it fixed.

**Comment by vincentrouleau** [comment]
Closing
