### ISSUE TITLE
[Minor issue] Still outputs tracking hidden div when theme.tracking is set

### ISSUE THREAD

**Issue by tintincastro** [hotdoy/grav-theme-hotdoy#19]
It seems the div should be enclosed with a conditional in the `partials/base.html.twig`, because as of now, it appears in the code whether or not you set the option.

Thanks you again for such a great theme and have a nice day !

**Comment by hotdoy** [comment]
Is this still an issue?

**Comment by vincentrouleau** [comment]
It's a way for me to check the theme version by simply inspecting the element when someone opens an issue.
No data is sent.
