### ISSUE TITLE
Make it a skeleton?

### ISSUE THREAD

**Issue by prinla** [hotdoy/grav-theme-hotdoy#2]
Hi, 
I really love the design of your theme...
Would it be possible to add it with your demo-content as a skeleton on getgrav?
Thanks for all your work,
Oliver

**Comment by vincentrouleau** [comment]
It's definitely on the table. Really just a matter of priority. But a _demo with a dump of the current content could be done quickly. I'll see what I can do in the next days.
Happy you like it!

**Comment by vincentrouleau** [comment]
@prinla the skeleton is available.
https://github.com/hotdoy/grav-skeleton-hotdoy
Check the latest release.
