### ISSUE TITLE
[Light issue]

### ISSUE THREAD

**Issue by anjichiban** [hotdoy/grav-theme-hotdoy#20]
Hello, 
thank you for you very nice theme.
I have a slight trouble with the drawers : when I collapse/uncollapse the drawer a second time, all the content i put inside just disappear like magic... !

Thanks for reading.
angel -

**Comment by jofemodo** [comment]
I can confirm the issue ...

**Comment by phz1** [comment]
Until this is fixed you can use [Shortcode UI Accordions](https://github.com/getgrav/grav-plugin-shortcode-ui#accordion) as an alternative.

**Comment by klorydryk** [comment]
Confirmed in v1.7.16
Grav v1.6.24
Shortcode Core v4.2.3

**Comment by vincentrouleau** [comment]
Is this still an issue?

**Comment by klorydryk** [comment]
Grav 1.6.25
Hotdoy 1.7.17
Still an issue :(

**Comment by vincentrouleau** [comment]
Make sure you have the latest version and I'll take a look this week. Is you guys have an example that could be great!

**Comment by klorydryk** [comment]
Yes, you can test there: https://angelip.fr/grav/page-modulaire

**Comment by vincentrouleau** [comment]
I was able to reproduce in Firefox only.  Expect a fix in the next patch. Probably tomorrow.

**Comment by vincentrouleau** [comment]
Should be fixed in v1.7.18.
Unfortunately, I had to remove pretty much all drawers animations on Firefox but it works.
