### ISSUE TITLE
Image loading & html5 audio

### ISSUE THREAD

**Issue by jofemodo** [hotdoy/grav-theme-hotdoy#22]
I'm having another bizarre problem:
When including some html5 audio clips in a page, images are not loaded all the time. Normally i have to do F5 for getting everything loaded.
If i remove the html5 clips, then everything works OK.
Ideas?

**Comment by jofemodo** [comment]
Ahhh! You can see how it work here:

http://noindexgoogle-web2.zynthian.org/use-cases/keyboard-expander

Remove the "noindexgoogle-" part ... ;-)

**Comment by vincentrouleau** [comment]
Weird Indeed. I never even an added audio file to a page and there is nothing in the code doing anything with them. There is, however, a script for lazy loading images. 
I'll check it out.

**Comment by vincentrouleau** [comment]
Can't seem to reproduce the issue. 
You could try to disable image lazyloading from the admin, in Hotdoy theme settings, all the way down the theme settings.

**Comment by vincentrouleau** [comment]
Closing
