### ISSUE TITLE
MaterialDesign/ MarkDown Buttons broken

### ISSUE THREAD

**Issue by buzzy3** [hotdoy/grav-theme-hotdoy#3]
Hi

Current; even I see you are on refactoring, neither Material Icons Set nor Normal Buttons on all of the theme / Links. works.

I also would be happy if you email me for a small $ task. buzzy3@mac.com 
But its a wonderful work you made.

![Bildschirmfoto 2019-12-08 um 17 59 02](https://user-images.githubusercontent.com/265888/70392898-a6ce5780-19e4-11ea-9103-7a1af6e3daaa.png)

**Comment by vincentrouleau** [comment]
Make sure you have the [shortcode core plugin](https://github.com/getgrav/grav-plugin-shortcode-core) installed. You could also check the plugin config and make sure the path to the theme specific shortcodes is correct.  (config should look something like [this](https://github.com/hotdoy/grav-skeleton-hotdoy/blob/master/config/plugins/shortcode-core.yaml)).
